# Generated by Django 3.2.5 on 2021-07-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_path',
            field=models.TextField(default='https://images.farmatodo.com/bduc/img/ve/item/medium/ve_items_111007226_medium_standart_1383877466813.jpg'),
            preserve_default=False,
        ),
    ]
